---
- name: Ensure rpmbuild directory structure exists
  ansible.builtin.file:
    path: "~/rpmbuild/{{ item }}"
    state: directory
  loop: [SPECS, RPMS, SOURCES, BUILD, SRPMS]

- name: Build repository release packages
  block:
    - name: Deploy the spec files
      ansible.builtin.template:
        src: "files/len-{{ item.short_name }}-release.spec"
        dest: "~/rpmbuild/SPECS/len-{{ item.short_name }}-release.spec"
        mode: '0644'
      vars:
        repo_version: "{{ item.version }}"
      loop: "{{ repositories }}"

    - name: Build the RPM packages
      ansible.builtin.command:
        cmd: "rpmbuild -bb ~/rpmbuild/SPECS/len-{{ item.short_name }}-release.spec"
        creates: "~/rpmbuild/RPMS/noarch/len-{{ item.short_name }}-release-{{ item.version }}-1.noarch.rpm"
      loop: "{{ repositories }}"

    - name: Copy the built RPMs to the repositories
      ansible.builtin.copy:
        src: "~/rpmbuild/RPMS/noarch/len-{{ item.short_name }}-release-{{ item.version }}-1.noarch.rpm"
        dest: "{{ repo_base }}/{{ item.short_name }}/"
        remote_src: yes
        mode: '0644'
      loop: "{{ repositories }}"

    - name: Update repository metadata
      ansible.builtin.command:
        cmd: "createrepo_c --update {{ repo_base }}/{{ item.short_name }}"
      loop: "{{ repositories }}"
