---
- name: Ensure rpmbuild directory structure exists
  ansible.builtin.file:
    path: "~/rpmbuild/{{ item }}"
    state: directory
  loop: [SPECS, RPMS, SOURCES, BUILD, SRPMS]
  tags: [rpm_creation]

- name: Build repository release packages
  tags: [rpm_creation]
  block:
    - name: Deploy the spec files
      ansible.builtin.template:
        src: "files/{{ spec_filename }}"
        dest: "~/rpmbuild/SPECS/{{ spec_filename }}"
        mode: '0644'

    - name: Build the RPM packages
      ansible.builtin.command:
        cmd: "rpmbuild -ba ~/rpmbuild/SPECS/{{ spec_filename }}"
        creates: "~/rpmbuild/RPMS/noarch/{{ distro_name }}-{{ spec_short_name }}-{{ spec_major_version }}.{{ spec_minor_version }}-{{ spec_release_version }}.noarch.rpm"

    - name: Copy the built RPMs to the repositories
      ansible.builtin.copy:
        src: "~/rpmbuild/RPMS/noarch/{{ distro_name }}-{{ spec_short_name }}-{{ spec_major_version }}.{{ spec_minor_version }}-{{ spec_release_version }}.el10.noarch.rpm"
        dest: "{{ repo_base }}/{{ spec_major_version }}/{{ item.path }}/"
        remote_src: yes
        mode: '0644'
      loop: "{{ repositories }}"

    - name: Copy the built SRPMs to the repositories
      ansible.builtin.copy:
        src: "~/rpmbuild/SRPMS/{{ distro_name }}-{{ spec_short_name }}-{{ spec_major_version }}.{{ spec_minor_version }}-{{ spec_release_version }}.el10.src.rpm"
        dest: "{{ repo_base }}/{{ spec_major_version }}/{{ item.sources.path }}/"
        remote_src: yes
        mode: '0644'
      loop: "{{ repositories }}"

    - name: Update repository metadata
      ansible.builtin.command:
        cmd: "createrepo_c --update {{ repo_base }}/{{ spec_major_version }}/{{ item.path }}"
      loop: "{{ repositories }}"

    - name: Update source repository metadata
      ansible.builtin.command:
        cmd: "createrepo_c --update {{ repo_base }}/{{ spec_major_version }}/{{ item.sources.path }}"
      loop: "{{ repositories }}"
